on:
  - 'push'

jobs:
  lint-and-test:
    runs-on: 'ubuntu-latest'
    name: 'Lint and test'
    container:
      image: 'rust:1.59-alpine'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - name: 'Install rustfmt'
        run: 'rustup component add rustfmt'
      - name: 'Check format with rustfmt'
        run: 'cargo fmt --check'
      - name: 'Test'
        run: 'cargo test'
